### ISSUE TITLE
ChartConfiguration not serializable?

### ISSUE THREAD

**Issue by VaclavC** [adessoAG/wicked-charts#151] opened 2018-07-23 13:24 UTC
Hello,

   I'am trying to use wicked-charts according to this [example](https://wicked-charts-showcase.appspot.com/chartjs/lineBasic).

   I'am getting error about serialization, however:

`[Wicket-AsyncPageStore-PageSavingThread] ERROR org.apache.wicket.serialize.java.JavaSerializer - Error serializing object class .... SOMETHING ...]
org.apache.wicket.core.util.objects.checker.CheckingObjectOutputStream$ObjectCheckException: The object type is not Serializable!
A problem occurred while checking object with type: de.adesso.wickedcharts.chartjs.ChartConfiguration`

What I'am doing wrong?

**Comment by martin-g** [comment] 2018-07-25 07:43
> My guess would be that your configuration class needs to implement Serializable.

AFAIU @VaclavC 's code uses (as in the examples):
https://github.com/adessoAG/wicked-charts/blob/master/chartjs-wrapper/src/main/java/de/adesso/wickedcharts/chartjs/ChartConfiguration.java

And this class doesn't implement `java.io.Serializable`, thus the error.

**Comment by maximAtanasov** [comment] 2018-07-25 07:57
@martin-g 
Yes, you are correct. This will be fixed in the next release.
We have always just extended this configuration in a separate class and implemented `Serializable` there. But it makes sense to have already have it in the base class. :)

**Comment by VaclavC** [comment] 2018-07-25 08:05
Exactly, I was using ChartConfiguration directly. I have created empty class extending it and implementing Serializable and the problem is now gone. Thank you both for your help.

**Comment by maximAtanasov** [comment] 2018-07-25 08:09
Yes, definitely a good idea. I will open a new issue for that :) . Thanks for pointing this out and I'm glad the issue is resolved.

**Closed by maximAtanasov** 2018-07-25 08:09 UTC
